/*
 * (C) Copyright 2007-2008 Michal Simek
 *
 * Michal SIMEK <monstr@monstr.eu>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 *
 * CAUTION: This file is automatically generated by libgen.
 * Version: Xilinx EDK 14.5 EDK_P.58f
 * Generate by U-BOOT v4.00.c
 * Project description at http://www.monstr.eu/uboot/
 */

#define XILINX_BOARD_NAME	"SDRDC"

/* ARM is ps7_cortexa9_0 */
#define XPAR_CPU_CORTEXA9_CORE_CLOCK_FREQ_HZ	666666687

/* Interrupt controller is ps7_scugic_0 */
#define XILINX_PS7_INTC_BASEADDR		0xf8f00100

/* System Timer Clock Frequency */
#define XILINX_PS7_CLOCK_FREQ	333333343

/* Uart console is ps7_uart_1 */
#define XILINX_PS7_UART
#define XILINX_PS7_UART_BASEADDR	0xe0001000
#define XILINX_PS7_UART_CLOCK_HZ	50000000

/* IIC pheriphery is ps7_i2c_0 */
#define XILINX_PS7_IIC_BASEADDR		0xe0004000

/* GPIO is gpio_sw*/
#define XILINX_GPIO_BASEADDR	0x41220000

/* SDIO controller is ps7_sd_0 */
#define XILINX_PS7_SDIO_BASEADDR		0xe0100000

/* Main Memory is ps7_ddr_0 */
#define XILINX_RAM_START	0x00000000
#define XILINX_RAM_SIZE		0x40000000

/* Flash Memory is ps7_qspi_0 */
#define XILINX_PS7_QSPI_FLASH_BASEADDR	0xE000D000
#define XILINX_SPI_FLASH_MAX_FREQ	50000000
#define XILINX_SPI_FLASH_CS	0

/* Sysace doesn't exist */

/* Ethernet controller is ps7_ethernet_0 */
#define XILINX_PS7_GEM_BASEADDR			0xe000b000


/* Definitions for peripheral DSNK_0 */
#define XPAR_DSNK_0_BASEADDR 0x43C30000
#define XPAR_DSNK_0_HIGHADDR 0x43C3FFFF


/* Definitions for peripheral DSRC_0 */
#define XPAR_DSRC_0_BASEADDR 0x43C00000
#define XPAR_DSRC_0_HIGHADDR 0x43C0FFFF

/* Definitions for peripheral AXI_DMAC_0 */
#define XPAR_AXI_DMAC_0_BASEADDR 0x7C400000
#define XPAR_AXI_DMAC_0_HIGHADDR 0x7C40FFFF


/* Definitions for peripheral AXI_DMAC_1 */
#define XPAR_AXI_DMAC_1_BASEADDR 0x7C420000
#define XPAR_AXI_DMAC_1_HIGHADDR 0x7C42FFFF


/* Definitions for peripheral AXI_DMAC_2 */
#define XPAR_AXI_DMAC_2_BASEADDR 0x7C440000
#define XPAR_AXI_DMAC_2_HIGHADDR 0x7C44FFFF


/* Definitions for peripheral AXI_DMAC_3 */
#define XPAR_AXI_DMAC_3_BASEADDR 0x7C460000
#define XPAR_AXI_DMAC_3_HIGHADDR 0x7C46FFFF


/* Definitions for driver AXIPMON */
#define XPAR_XAXIPMON_NUM_INSTANCES 1

/* Definitions for peripheral AXI_PERF_MON_0 */
#define XPAR_AXI_PERF_MON_0_DEVICE_ID 0
#define XPAR_AXI_PERF_MON_0_BASEADDR 0x43C10000
#define XPAR_AXI_PERF_MON_0_HIGHADDR 0x43C1FFFF
#define XPAR_AXI_PERF_MON_0_GLOBAL_COUNT_WIDTH 64
#define XPAR_AXI_PERF_MON_0_METRICS_SAMPLE_COUNT_WIDTH 32
#define XPAR_AXI_PERF_MON_0_ENABLE_EVENT_COUNT 1
#define XPAR_AXI_PERF_MON_0_NUM_MONITOR_SLOTS 2
#define XPAR_AXI_PERF_MON_0_NUM_OF_COUNTERS 10
#define XPAR_AXI_PERF_MON_0_HAVE_SAMPLED_METRIC_CNT 1
#define XPAR_AXI_PERF_MON_0_ENABLE_EVENT_LOG 0
#define XPAR_AXI_PERF_MON_0_FIFO_AXIS_DEPTH 32
#define XPAR_AXI_PERF_MON_0_FIFO_AXIS_TDATA_WIDTH 56
#define XPAR_AXI_PERF_MON_0_FIFO_AXIS_TID_WIDTH 1
#define XPAR_AXI_PERF_MON_0_METRIC_COUNT_SCALE 1
#define XPAR_AXI_PERF_MON_0_ENABLE_ADVANCED 1
#define XPAR_AXI_PERF_MON_0_ENABLE_PROFILE 0
#define XPAR_AXI_PERF_MON_0_ENABLE_TRACE 0
#define XPAR_AXI_PERF_MON_0_S_AXI4_BASEADDR 0xFFFFFFFF
#define XPAR_AXI_PERF_MON_0_S_AXI4_HIGHADDR 0x00000000


