#
# Makefile -- Build instructions for PetaLogix AutoConfig MicroBlaze system
#

# Collect default rules for building the system from vendors/PetaLogix/common
include $(VEND)/PetaLogix/common/common.mak

# Insert manual overrides or extensions of build targets below

romfs::

clean::

