#!/bin/sh
# Init script for AD9361 tool using legacy ADI driver
#
# Copyright 2013,2014 Silver Bullet Technology
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
# file except in compliance with the License.  You may obtain a copy of the License at:
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the specific language governing
# permissions and limitations under the License.

# Enable FIR filters

ad9361 -d0 set_filter_fir_config             wb_wimax
ad9361 -d0 set_in_out_voltage_filter_fir_en  1
ad9361 -d0 set_filter_fir_config             wb_wimax
ad9361 -d0 get_filter_fir_config

# Setup AD1 for 4MSPS
ad9361 -d0 set_out_voltage_sampling_frequency 4000000
ad9361 -d0 get_out_voltage_sampling_frequency
ad9361 -d0 set_in_voltage_sampling_frequency  4000000
ad9361 -d0 get_in_voltage_sampling_frequency

# Enable FIR filters

ad9361 -d1 set_filter_fir_config             wb_wimax
ad9361 -d1 set_in_out_voltage_filter_fir_en  1
ad9361 -d1 set_filter_fir_config             wb_wimax
ad9361 -d1 get_filter_fir_config

# Setup AD1 for 4MSPS
ad9361 -d1 set_out_voltage_sampling_frequency 4000000
ad9361 -d1 get_out_voltage_sampling_frequency
ad9361 -d1 set_in_voltage_sampling_frequency  4000000
ad9361 -d1 get_in_voltage_sampling_frequency

# load the example waveform and stream continuously across all TX channels
dma_streamer_app adt /usr/lib/ad9361/data/802.16d-64q-cp16.iqw cont
