/** \file      ad9361.v
 *  \brief     Shared-library exports and version control
 *  \copyright Copyright 2013,2014 Silver Bullet Technology
 *
 *             Licensed under the Apache License, Version 2.0 (the "License"); you may not
 *             use this file except in compliance with the License.  You may obtain a copy
 *             of the License at: 
 *               http://www.apache.org/licenses/LICENSE-2.0
 *
 *             Unless required by applicable law or agreed to in writing, software
 *             distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 *             WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 *             License for the specific language governing permissions and limitations
 *             under the License.
 *
 * vim:ts=4:noexpandtab
 */
ad9361_0.1 {
	global:
		/* src/lib/common.c */
		CMB_init;
		CMB_SPIWriteField;
		CMB_SPIWriteByte;
		CMB_SPIReadByte;
		CMB_uartSendString;
		CMB_hostTxPacket;
		CMB_hostRxPacket;
		CMB_DelayU;
		CMB_gpioInit;
		CMB_gpioWrite;
		CMB_gpioPulse;
		ad9361_err_desc;
		/* src/lib/ad9361_hal.c */
		ad9361_hal_attach;
		ad9361_hal_detach;
		ad9361_hal_spi_reg_get;
		ad9361_hal_spi_reg_clr;
		/* src/lib/ad9361_hal_linux_dev.c */
		ad9361_hal_linux_attach;
		/* src/lib/ad9361_hal_linux_legacy.c */
		ad9361_hal_linux_cleanup;
		ad9361_hal_linux_gpio_init;
		ad9361_hal_linux_gpio_done;
		ad9361_hal_linux_spi_init;
		ad9361_hal_linux_spi_done;
		ad9361_hal_linux_uart_init;
		ad9361_hal_linux_uart_done;
		/* src/lib/ad9361_hal_sim.c */
		ad9361_hal_sim_attach;
	local:
		*;
};

ad9361_0.2 {
	global:
		/* src/lib/ad9361_debugfs.c */
		ad9361_get_bist_prbs;
		ad9361_set_bist_prbs;
		ad9361_get_bist_tone;
		ad9361_set_bist_tone;
		ad9361_get_gaininfo_rx1;
		ad9361_get_gaininfo_rx2;
		ad9361_get_gaininfo_rx;
		ad9361_set_initialize;
		ad9361_get_loopback;
		ad9361_set_loopback;
		ad9361_get_bist_timing_analysis;
		ad9361_get_frequency_division_duplex_mode_enable;
		ad9361_set_frequency_division_duplex_mode_enable;
		ad9361_get_ensm_enable_pin_pulse_mode_enable;
		ad9361_set_ensm_enable_pin_pulse_mode_enable;
		ad9361_get_ensm_enable_txnrx_control_enable;
		ad9361_set_ensm_enable_txnrx_control_enable;
		ad9361_get_debug_mode_enable;
		ad9361_set_debug_mode_enable;
		ad9361_get_tdd_use_fdd_vco_tables_enable;
		ad9361_set_tdd_use_fdd_vco_tables_enable;
		ad9361_get_tdd_use_dual_synth_mode_enable;
		ad9361_set_tdd_use_dual_synth_mode_enable;
		ad9361_get_tdd_skip_vco_cal_enable;
		ad9361_set_tdd_skip_vco_cal_enable;
		ad9361_get_2rx_2tx_mode_enable;
		ad9361_set_2rx_2tx_mode_enable;
		ad9361_get_split_gain_table_mode_enable;
		ad9361_set_split_gain_table_mode_enable;
		ad9361_get_rx_rf_port_input_select;
		ad9361_set_rx_rf_port_input_select;
		ad9361_get_tx_rf_port_input_select;
		ad9361_set_tx_rf_port_input_select;
		ad9361_get_external_tx_lo_enable;
		ad9361_set_external_tx_lo_enable;
		ad9361_get_external_rx_lo_enable;
		ad9361_set_external_rx_lo_enable;
		ad9361_get_xo_disable_use_ext_refclk_enable;
		ad9361_set_xo_disable_use_ext_refclk_enable;
		ad9361_get_clk_output_mode_select;
		ad9361_set_clk_output_mode_select;
		ad9361_get_dc_offset_tracking_update_event_mask;
		ad9361_set_dc_offset_tracking_update_event_mask;
		ad9361_get_dc_offset_attenuation_high_range;
		ad9361_set_dc_offset_attenuation_high_range;
		ad9361_get_dc_offset_attenuation_low_range;
		ad9361_set_dc_offset_attenuation_low_range;
		ad9361_get_dc_offset_count_high_range;
		ad9361_set_dc_offset_count_high_range;
		ad9361_get_dc_offset_count_low_range;
		ad9361_set_dc_offset_count_low_range;
		ad9361_get_rf_rx_bandwidth_hz;
		ad9361_set_rf_rx_bandwidth_hz;
		ad9361_get_rf_tx_bandwidth_hz;
		ad9361_set_rf_tx_bandwidth_hz;
		ad9361_get_tx_attenuation_mdB;
		ad9361_set_tx_attenuation_mdB;
		ad9361_get_update_tx_gain_in_alert_enable;
		ad9361_set_update_tx_gain_in_alert_enable;
		ad9361_get_gc_rx1_mode;
		ad9361_set_gc_rx1_mode;
		ad9361_get_gc_rx2_mode;
		ad9361_set_gc_rx2_mode;
		ad9361_get_gc_adc_ovr_sample_size;
		ad9361_set_gc_adc_ovr_sample_size;
		ad9361_get_gc_adc_small_overload_thresh;
		ad9361_set_gc_adc_small_overload_thresh;
		ad9361_get_gc_adc_large_overload_thresh;
		ad9361_set_gc_adc_large_overload_thresh;
		ad9361_get_gc_lmt_overload_high_thresh;
		ad9361_set_gc_lmt_overload_high_thresh;
		ad9361_get_gc_lmt_overload_low_thresh;
		ad9361_set_gc_lmt_overload_low_thresh;
		ad9361_get_gc_dec_pow_measurement_duration;
		ad9361_set_gc_dec_pow_measurement_duration;
		ad9361_get_gc_low_power_thresh;
		ad9361_set_gc_low_power_thresh;
		ad9361_get_gc_dig_gain_enable;
		ad9361_set_gc_dig_gain_enable;
		ad9361_get_gc_max_dig_gain;
		ad9361_set_gc_max_dig_gain;
		ad9361_get_mgc_rx1_ctrl_inp_enable;
		ad9361_set_mgc_rx1_ctrl_inp_enable;
		ad9361_get_mgc_rx2_ctrl_inp_enable;
		ad9361_set_mgc_rx2_ctrl_inp_enable;
		ad9361_get_mgc_inc_gain_step;
		ad9361_set_mgc_inc_gain_step;
		ad9361_get_mgc_dec_gain_step;
		ad9361_set_mgc_dec_gain_step;
		ad9361_get_mgc_split_table_ctrl_inp_gain_mode;
		ad9361_set_mgc_split_table_ctrl_inp_gain_mode;
		ad9361_get_agc_attack_delay_extra_margin_us;
		ad9361_set_agc_attack_delay_extra_margin_us;
		ad9361_get_agc_outer_thresh_high;
		ad9361_set_agc_outer_thresh_high;
		ad9361_get_agc_outer_thresh_high_dec_steps;
		ad9361_set_agc_outer_thresh_high_dec_steps;
		ad9361_get_agc_inner_thresh_high;
		ad9361_set_agc_inner_thresh_high;
		ad9361_get_agc_inner_thresh_high_dec_steps;
		ad9361_set_agc_inner_thresh_high_dec_steps;
		ad9361_get_agc_inner_thresh_low;
		ad9361_set_agc_inner_thresh_low;
		ad9361_get_agc_inner_thresh_low_inc_steps;
		ad9361_set_agc_inner_thresh_low_inc_steps;
		ad9361_get_agc_outer_thresh_low;
		ad9361_set_agc_outer_thresh_low;
		ad9361_get_agc_outer_thresh_low_inc_steps;
		ad9361_set_agc_outer_thresh_low_inc_steps;
		ad9361_get_agc_adc_small_overload_exceed_counter;
		ad9361_set_agc_adc_small_overload_exceed_counter;
		ad9361_get_agc_adc_large_overload_exceed_counter;
		ad9361_set_agc_adc_large_overload_exceed_counter;
		ad9361_get_agc_adc_large_overload_inc_steps;
		ad9361_set_agc_adc_large_overload_inc_steps;
		ad9361_get_agc_adc_lmt_small_overload_prevent_gain_inc_enable;
		ad9361_set_agc_adc_lmt_small_overload_prevent_gain_inc_enable;
		ad9361_get_agc_lmt_overload_large_exceed_counter;
		ad9361_set_agc_lmt_overload_large_exceed_counter;
		ad9361_get_agc_lmt_overload_small_exceed_counter;
		ad9361_set_agc_lmt_overload_small_exceed_counter;
		ad9361_get_agc_lmt_overload_large_inc_steps;
		ad9361_set_agc_lmt_overload_large_inc_steps;
		ad9361_get_agc_dig_saturation_exceed_counter;
		ad9361_set_agc_dig_saturation_exceed_counter;
		ad9361_get_agc_dig_gain_step_size;
		ad9361_set_agc_dig_gain_step_size;
		ad9361_get_agc_sync_for_gain_counter_enable;
		ad9361_set_agc_sync_for_gain_counter_enable;
		ad9361_get_agc_gain_update_interval_us;
		ad9361_set_agc_gain_update_interval_us;
		ad9361_get_agc_immed_gain_change_if_large_adc_overload_enable;
		ad9361_set_agc_immed_gain_change_if_large_adc_overload_enable;
		ad9361_get_agc_immed_gain_change_if_large_lmt_overload_enable;
		ad9361_set_agc_immed_gain_change_if_large_lmt_overload_enable;
		ad9361_get_fagc_dec_pow_measurement_duration;
		ad9361_set_fagc_dec_pow_measurement_duration;
		ad9361_get_fagc_state_wait_time_ns;
		ad9361_set_fagc_state_wait_time_ns;
		ad9361_get_fagc_allow_agc_gain_increase_enable;
		ad9361_set_fagc_allow_agc_gain_increase_enable;
		ad9361_get_fagc_lp_thresh_increment_time;
		ad9361_set_fagc_lp_thresh_increment_time;
		ad9361_get_fagc_lp_thresh_increment_steps;
		ad9361_set_fagc_lp_thresh_increment_steps;
		ad9361_get_fagc_lock_level;
		ad9361_set_fagc_lock_level;
		ad9361_get_fagc_lock_level_lmt_gain_increase_enable;
		ad9361_set_fagc_lock_level_lmt_gain_increase_enable;
		ad9361_get_fagc_lock_level_gain_increase_upper_limit;
		ad9361_set_fagc_lock_level_gain_increase_upper_limit;
		ad9361_get_fagc_lpf_final_settling_steps;
		ad9361_set_fagc_lpf_final_settling_steps;
		ad9361_get_fagc_lmt_final_settling_steps;
		ad9361_set_fagc_lmt_final_settling_steps;
		ad9361_get_fagc_final_overrange_count;
		ad9361_set_fagc_final_overrange_count;
		ad9361_get_fagc_gain_increase_after_gain_lock_enable;
		ad9361_set_fagc_gain_increase_after_gain_lock_enable;
		ad9361_get_fagc_gain_index_type_after_exit_rx_mode;
		ad9361_set_fagc_gain_index_type_after_exit_rx_mode;
		ad9361_get_fagc_use_last_lock_level_for_set_gain_enable;
		ad9361_set_fagc_use_last_lock_level_for_set_gain_enable;
		ad9361_get_fagc_rst_gla_stronger_sig_thresh_exceeded_enable;
		ad9361_set_fagc_rst_gla_stronger_sig_thresh_exceeded_enable;
		ad9361_get_fagc_optimized_gain_offset;
		ad9361_set_fagc_optimized_gain_offset;
		ad9361_get_fagc_rst_gla_stronger_sig_thresh_above_ll;
		ad9361_set_fagc_rst_gla_stronger_sig_thresh_above_ll;
		ad9361_get_fagc_rst_gla_engergy_lost_sig_thresh_exceeded_enable;
		ad9361_set_fagc_rst_gla_engergy_lost_sig_thresh_exceeded_enable;
		ad9361_get_fagc_rst_gla_engergy_lost_goto_optim_gain_enable;
		ad9361_set_fagc_rst_gla_engergy_lost_goto_optim_gain_enable;
		ad9361_get_fagc_rst_gla_engergy_lost_sig_thresh_below_ll;
		ad9361_set_fagc_rst_gla_engergy_lost_sig_thresh_below_ll;
		ad9361_get_fagc_energy_lost_stronger_sig_gain_lock_exit_cnt;
		ad9361_set_fagc_energy_lost_stronger_sig_gain_lock_exit_cnt;
		ad9361_get_fagc_rst_gla_large_adc_overload_enable;
		ad9361_set_fagc_rst_gla_large_adc_overload_enable;
		ad9361_get_fagc_rst_gla_large_lmt_overload_enable;
		ad9361_set_fagc_rst_gla_large_lmt_overload_enable;
		ad9361_get_fagc_rst_gla_en_agc_pulled_high_enable;
		ad9361_set_fagc_rst_gla_en_agc_pulled_high_enable;
		ad9361_get_fagc_rst_gla_if_en_agc_pulled_high_mode;
		ad9361_set_fagc_rst_gla_if_en_agc_pulled_high_mode;
		ad9361_get_fagc_power_measurement_duration_in_state5;
		ad9361_set_fagc_power_measurement_duration_in_state5;
		ad9361_get_rssi_restart_mode;
		ad9361_set_rssi_restart_mode;
		ad9361_get_rssi_unit_is_rx_samples_enable;
		ad9361_set_rssi_unit_is_rx_samples_enable;
		ad9361_get_rssi_delay;
		ad9361_set_rssi_delay;
		ad9361_get_rssi_wait;
		ad9361_set_rssi_wait;
		ad9361_get_rssi_duration;
		ad9361_set_rssi_duration;
		ad9361_get_ctrl_outs_index;
		ad9361_set_ctrl_outs_index;
		ad9361_get_ctrl_outs_enable_mask;
		ad9361_set_ctrl_outs_enable_mask;
		ad9361_get_elna_settling_delay_ns;
		ad9361_set_elna_settling_delay_ns;
		ad9361_get_elna_gain_mdB;
		ad9361_set_elna_gain_mdB;
		ad9361_get_elna_bypass_loss_mdB;
		ad9361_set_elna_bypass_loss_mdB;
		ad9361_get_elna_rx1_gpo0_control_enable;
		ad9361_set_elna_rx1_gpo0_control_enable;
		ad9361_get_elna_rx2_gpo1_control_enable;
		ad9361_set_elna_rx2_gpo1_control_enable;
		ad9361_get_temp_sense_measurement_interval_ms;
		ad9361_set_temp_sense_measurement_interval_ms;
		ad9361_get_temp_sense_offset_signed;
		ad9361_set_temp_sense_offset_signed;
		ad9361_get_temp_sense_periodic_measurement_enable;
		ad9361_set_temp_sense_periodic_measurement_enable;
		ad9361_get_temp_sense_decimation;
		ad9361_set_temp_sense_decimation;
		ad9361_get_aux_adc_rate;
		ad9361_set_aux_adc_rate;
		ad9361_get_aux_adc_decimation;
		ad9361_set_aux_adc_decimation;
		ad9361_get_aux_dac_manual_mode_enable;
		ad9361_set_aux_dac_manual_mode_enable;
		ad9361_get_aux_dac1_default_value_mV;
		ad9361_set_aux_dac1_default_value_mV;
		ad9361_get_aux_dac1_active_in_rx_enable;
		ad9361_set_aux_dac1_active_in_rx_enable;
		ad9361_get_aux_dac1_active_in_tx_enable;
		ad9361_set_aux_dac1_active_in_tx_enable;
		ad9361_get_aux_dac1_active_in_alert_enable;
		ad9361_set_aux_dac1_active_in_alert_enable;
		ad9361_get_aux_dac1_rx_delay_us;
		ad9361_set_aux_dac1_rx_delay_us;
		ad9361_get_aux_dac1_tx_delay_us;
		ad9361_set_aux_dac1_tx_delay_us;
		ad9361_get_aux_dac2_default_value_mV;
		ad9361_set_aux_dac2_default_value_mV;
		ad9361_get_aux_dac2_active_in_rx_enable;
		ad9361_set_aux_dac2_active_in_rx_enable;
		ad9361_get_aux_dac2_active_in_tx_enable;
		ad9361_set_aux_dac2_active_in_tx_enable;
		ad9361_get_aux_dac2_active_in_alert_enable;
		ad9361_set_aux_dac2_active_in_alert_enable;
		ad9361_get_aux_dac2_rx_delay_us;
		ad9361_set_aux_dac2_rx_delay_us;
		ad9361_get_aux_dac2_tx_delay_us;
		ad9361_set_aux_dac2_tx_delay_us;
		/* src/lib/common.c */
		ad9361_legacy_dev;
		/* src/lib/ad9361_hal.c */
		ad9361_hal;
		ad9361_spi_write_byte;
		ad9361_spi_read_byte;
		ad9361_gpio_write;
		ad9361_sysfs_read;
		ad9361_sysfs_write;
		/* src/lib/ad9361_hal_linux_dev.c */
		ad9361_hal_linux_init;
		ad9361_hal_linux_done;
		ad9361_hal_linux_dev_gpio_init;
		ad9361_hal_linux_dev_gpio_done;
		ad9361_hal_linux_dev_spi_init;
		ad9361_hal_linux_dev_spi_done;
		ad9361_hal_linux_dev_sysfs_init;
		ad9361_hal_linux_dev_sysfs_done;
		ad9361_hal_linux_dev_defaults_set_spidev;
		ad9361_hal_linux_dev_defaults_set_gpio;
	local:
		*;
};
