
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSM.
* Version: 
* DO NOT EDIT.
*
*  v (64-bit)
SW Build (by ) on 
Copyright 1986-2014 Xilinx, Inc. All Rights Reserved.
* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xaxipmon.h"

/*
* The configuration table for devices
*/

XAxiPmon_Config XAxiPmon_ConfigTable[] =
{
	{
#ifdef XPAR_AXI_PERF_MON_0_DEVICE_ID
		XPAR_AXI_PERF_MON_0_DEVICE_ID,
		XPAR_AXI_PERF_MON_0_BASEADDR,
		XPAR_AXI_PERF_MON_0_GLOBAL_COUNT_WIDTH,
		XPAR_AXI_PERF_MON_0_METRICS_SAMPLE_COUNT_WIDTH,
		XPAR_AXI_PERF_MON_0_ENABLE_EVENT_COUNT,
		XPAR_AXI_PERF_MON_0_NUM_MONITOR_SLOTS,
		XPAR_AXI_PERF_MON_0_NUM_OF_COUNTERS,
		XPAR_AXI_PERF_MON_0_HAVE_SAMPLED_METRIC_CNT,
		XPAR_AXI_PERF_MON_0_ENABLE_EVENT_LOG,
		XPAR_AXI_PERF_MON_0_FIFO_AXIS_DEPTH,
		XPAR_AXI_PERF_MON_0_FIFO_AXIS_TDATA_WIDTH,
		XPAR_AXI_PERF_MON_0_FIFO_AXIS_TID_WIDTH,
		XPAR_AXI_PERF_MON_0_METRIC_COUNT_SCALE,
		XPAR_AXI_PERF_MON_0_ENABLE_ADVANCED,
		XPAR_AXI_PERF_MON_0_ENABLE_PROFILE,
		XPAR_AXI_PERF_MON_0_ENABLE_TRACE
#else
		~0
#endif
	}
};


